/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg50_gui09;

/**
 *
 * @author Gerardo
 */
import javax.swing.DefaultListModel; //nuevo
import javax.swing.JOptionPane;
import javax.swing.ListModel;
public class Principal extends javax.swing.JFrame {
    //declaracion de variables globales (aquellas que esta disponibles
    //desde cualquier evento, metodo o funcion de esta clase)
    //para este caso vamos a declarar una variable global llamada
    //modelo1 que debe estar disponible desde cualquier evento
    DefaultListModel modelo1;
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        caja1 = new javax.swing.JTextField();
        botonAgregar1 = new javax.swing.JButton();
        botonAgregar2 = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerardo 20012002049");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lista1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lista1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Sistemas", "Industrial", "Derecho", "Civil", "Letras" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lista1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lista1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nuevo Color:");

        caja1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        botonAgregar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonAgregar1.setText("Agregar (metodo 1)");
        botonAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregar1ActionPerformed(evt);
            }
        });

        botonAgregar2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonAgregar2.setText("Agregar (metodo 2)");
        botonAgregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregar2ActionPerformed(evt);
            }
        });

        botonEditar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonEditar.setText("Editar");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        botonBorrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonBorrar.setText("Borrar");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonLimpiar.setText("Limpiar");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caja1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAgregar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonAgregar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(caja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAgregar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAgregar2)
                        .addGap(37, 37, 37)
                        .addComponent(botonEditar)
                        .addGap(37, 37, 37)
                        .addComponent(botonBorrar)
                        .addGap(54, 54, 54)
                        .addComponent(botonLimpiar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        //dar memoria al modelo
        modelo1 = new DefaultListModel();
        
        /*
        //ESTO NO ES TEMA DE ESTA ASIGNAGTURA
        //preservar el modelo anterior: copiar los items del modelo anterior al nuevo modelo
        //OJO: esto requiere conocimientos de abstraccion y polimorfismo
        for( int i = 0; i < lista1.getModel().getSize(); i++ )
            modelo1.addElement( lista1.getModel().getElementAt(i).toString() );
        //ESTO NO ES TEMA DE ESTA ASIGNAGTURA
        */
        
        //llenar los items de modelo1
        modelo1.addElement("Rojo");
        modelo1.addElement("Verde");
        modelo1.addElement("Azul");
        modelo1.addElement("Gris");
        modelo1.addElement("Amarillo");
        modelo1.addElement("Blanco");
        modelo1.addElement("Negro");
        //apuntar el modelo1 hacia la lista
        lista1.setModel(modelo1);
    }//GEN-LAST:event_formWindowOpened

    private void botonAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregar1ActionPerformed
        //Agregar a lista1 lo que se escriba en caja1
        //impedir agregar texto en blanco
        if( caja1.getText().trim().length() > 0 ){
            modelo1.addElement( caja1.getText() );
            //limpiar la caja de texto
            caja1.setText("");
        }
        else
            JOptionPane.showMessageDialog(this, "Debe escribir algo en la caja");
    }//GEN-LAST:event_botonAgregar1ActionPerformed

    private void botonAgregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregar2ActionPerformed
        //Agregar a lista1 usando un InputDialog
        String str = JOptionPane.showInputDialog(this,"Digite el nombre del color");
        //si hizo click en Cancelar o en cerrar (X) str toma el valor null
        if( str != null ){
            if( str.trim().length() > 0 ){
                modelo1.addElement(str);
            }
            else
                JOptionPane.showMessageDialog(this, "Debe escribir el color");
        }
    }//GEN-LAST:event_botonAgregar2ActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        //verificar si se ha seleccionado un item
        if( lista1.getSelectedIndex() == -1 )
            JOptionPane.showMessageDialog(this, "Debe seleccionar un item");
        else{
            //hay item seleccionado
            //recuperar el texto del item seleccionado
            String str = lista1.getSelectedValue();
            //mostrar un cuadro para editar
            String nuevo = JOptionPane.showInputDialog(this,"Digite el nuevo valor",str);
            if( nuevo != null ){
                if( nuevo.trim().length() > 0 ){
                    //reemplazar el valor en el modelo
                    modelo1.setElementAt(nuevo, lista1.getSelectedIndex());
                }
                else
                    JOptionPane.showMessageDialog(this, "No se acepta texto en blanco.");
            }
        }
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        //verificar si se ha seleccionado un item
        if( lista1.getSelectedIndex() == -1 )
            JOptionPane.showMessageDialog(this, "Debe seleccionar un item");
        else{
            //preguntar al usuario si desea borrar
            int boton = JOptionPane.showConfirmDialog(this, "Desea borrar el item?");
            //si hace click en el boton 0 es porque dijo que si (Yes)
            if( boton == 0 ){
                //eliminar del modelo el item en la posicion seleccionado en la lista
                modelo1.removeElementAt(lista1.getSelectedIndex());
            }
        }
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        //preguntar al usuario si desea borrar
        int boton = JOptionPane.showConfirmDialog(this, "Desea limpiar toda la lista?");
        //si hace click en el boton 0 es porque dijo que si (Yes)
        if( boton == 0 ){
            modelo1.removeAllElements();
        }
    }//GEN-LAST:event_botonLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar1;
    private javax.swing.JButton botonAgregar2;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JTextField caja1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lista1;
    // End of variables declaration//GEN-END:variables
}
